monolog:
    handlers:
        stream:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        buffered:
            type:     buffer
            # handler:  easylog
            handler: stream
            channels: ["!event"]
        # easylog:
        #     type: service
        #     id:   easycorp.easylog.handler
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']

# services:
#     easycorp.easylog.handler:
#         class: EasyCorp\EasyLog\EasyLogHandler
#         public: false
#         arguments:
#             - '%kernel.logs_dir%/%kernel.environment%/site.log'
