monolog:
    handlers:
        stream:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
        buffered:
            type:     buffer
            # handler:  easylog
            handler: stream
            channels: ["!event"]
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%/site.log'
            level: debug
            formatter: eccube.log.formatter.line
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
