web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler:
        enabled: true
        only_exceptions: false
        collect: true
        # プロファイラーの保存先を明示的に指定
        storage:
            dsn: 'file:%kernel.cache_dir%/profiler'