when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler: 
            enabled: true
            collect: true
            only_exceptions: false
            # プロファイラーの保存先を直接指定
            dsn: 'file:%kernel.cache_dir%/profiler'