services:
    Plugin\GmoPaymentGateway4\Service\Method\CreditCard:
        class: Plugin\GmoPaymentGateway4\Service\Method\CreditCard
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $orderStatusRepository: '@Eccube\Repository\Master\OrderStatusRepository'
            $shoppingPurchaseFlow: '@Eccube\Service\PurchaseFlow\PurchaseFlow'
            $paymentHelperCredit: '@Plugin\GmoPaymentGateway4\Service\PaymentHelperCredit'
            $paymentHelperMember: '@Plugin\GmoPaymentGateway4\Service\PaymentHelperMember'
        public: true
        autowire: false
        tags:
            - 'app.payment_method'
