security:
    password_hashers:
        legacy:
            algorithm: sha256
            encode_as_base64: false
            iterations: 1

        # Eccube\Entity\Customer:
        #     # algorithm: sodium
        #     algorithm: bcrypt
        #     migrate_from:
        #         - bcrypt
        #         - legacy

        # App\Hasher\LegacyCustomerPasswordHasher:
        #     id: App\Hasher\LegacyCustomerPasswordHasher

        Eccube\Entity\Member:
            # algorithm: sodium
            algorithm: bcrypt
            migrate_from:
                - bcrypt

        # Eccube\Entity\Customer:
        #     algorithm: auto
        #     migrate_from:
        #         - App\Hasher\LegacyCustomerPasswordHasher
        #         - bcrypt
        Eccube\Entity\Customer:
            algorithm: auto
            migrate_from:
                - 'legacy_hasher'
                - bcrypt

    providers:
        # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
        # In this example, users are stored via Doctrine in the database
        # To see the users at src/App/DataFixtures/ORM/LoadFixtures.php
        # To load users from somewhere else: https://symfony.com/doc/current/security/custom_provider.html
        member_provider:
            id: Eccube\Security\Core\User\MemberProvider
        customer_provider:
            id: Eccube\Security\Core\User\CustomerProvider
    # https://symfony.com/doc/current/security.html#initial-security-yml-setup-authentication
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: '^/%eccube_admin_route%'
            # lazy: true
            provider: member_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                enable_csrf: true
                default_target_path: /%eccube_admin_route%/
                username_parameter: 'login_id'
                password_parameter: 'password'
                use_forward: false
                success_handler: app.eccube.security.success_handler
                failure_handler: eccube.security.failure_handler
            logout:
                path: admin_logout
                target: admin_login
        adoption:
            pattern: '^/adoption/'
            lazy: true
            provider: customer_provider
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 3600
                name: eccube_remember_me
                remember_me_parameter: 'login_memory'
            form_login:
                # check_path: adoption_login
                login_path: adoption_login
                check_path: /adoption/login
                # login_path: /adoption/login
                enable_csrf: true
                default_target_path: adoption_mypage
                username_parameter: 'login_email'
                password_parameter: 'login_pass'
                use_forward: false
                success_handler: app.eccube.security.success_handler
                failure_handler: eccube.security.failure_handler
            logout:
                path: logout
                target: adoption_top
        breeder:
            pattern: '^/breeder/'
            lazy: true
            provider: customer_provider
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 3600
                name: eccube_remember_me
                remember_me_parameter: 'login_memory'
            form_login:
                check_path: breeder_login
                login_path: breeder_login
                enable_csrf: true
                default_target_path: breeder_mypage
                username_parameter: 'login_email'
                password_parameter: 'login_pass'
                use_forward: false
                success_handler: app.eccube.security.success_handler
                failure_handler: eccube.security.failure_handler
            logout:
                path: logout
                target: breeder_top
        customer:
            pattern: '^/'
            lazy: true
            provider: customer_provider
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 3600
                name: eccube_remember_me
                remember_me_parameter: 'login_memory'
            form_login:
                check_path: mypage_login
                login_path: mypage_login
                enable_csrf: true
                default_target_path: homepage
                username_parameter: 'login_email'
                password_parameter: 'login_pass'
                use_forward: false
                success_handler: app.eccube.security.success_handler
                failure_handler: eccube.security.failure_handler
            logout:
                path: logout
                target: homepage
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false
